### ISSUE TITLE
Might be nice to include Xarray interface as well

### ISSUE THREAD

**Issue by agstephens** [MariaRusso/CF-CIS-Iris_python_tools#1]
Xarray already has an interface to Iris. 

Might be useful to have a similar interface to/from CF objects (unless it already exists).

**Comment by MariaRusso** [comment]
I've heard of Xarray but I am not very familiar with it. If I get a chance I'll look into it; it should be fairly easy to convert from CF to Xarray.

**Comment by agstephens** [comment]
Thanks @MariaRusso, here is the Iris interface:

https://xarray.pydata.org/en/stable/generated/xarray.DataArray.to_iris.html

https://xarray.pydata.org/en/stable/generated/xarray.DataArray.from_iris.html

**Comment by MariaRusso** [comment]
Hi @agstephens,
I've now added an extra function, xarray_from_cf, to convert_CFvars.py.
This should be straightforward to use (see README file), but let me know if you encounter any problems.

**Comment by agstephens** [comment]
@MariaRusso Thanks for keeping me updated on this. It looks useful. 👍
